version: '3'
services:
  backend-service:
    build: ./
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432

  postgres:
    image: postgres:9.4
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=productdb"
    volumes:
      - ./init-scripts/data.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    expose:
      - 5432

 
