version: '3'
services:
  web: 
    build: './tfg-front'
    ports: 
      - 80:80
    environment:
        - BACKEND_HOST=postgres


  product-service:
    build: ./
    ports:
      - "8088:8088"
    environment:
      - WAIT_HOSTS=postgres:5432
      - DATABASE_HOST=postgres

    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres:9.4
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_DB=postgres"
    ports:
      - "5432:5432"
    expose:
      - 5432