server:
  port: 8088

jwt:
  secret: secret
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/postgres
    username: postgres
    password: root
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      generate-ddl: true
      ddl-auto: create

    defer-datasource-initialization: true


springdoc:
  swagger-ui:
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true
    path: /swagger
  api-docs:
    path: /swagger-docs
  packages-to-scan: ual.tfg.monolith.controller