server:
  port: 80

jwt:
  secret: secret
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:5432/postgres
    username: postgres
    password: root
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      generate-ddl: true
      ddl-auto: create

    defer-datasource-initialization: true


springdoc:
  swagger-ui:
    tryItOutEnabled: true
    operationsSorter: method
    tagsSorter: alpha
    filter: true
    path: /swagger
  api-docs:
    path: /swagger-docs
  packages-to-scan: ual.tfg.monolith.controller

paypal:
  baseUrl: https://api-m.sandbox.paypal.com
  clientId: AQeCPaz9NEJqDQEg6KX3EKZ7u5uXxmK3nvCPXcb7vMx79W_fj9Mnx_tPb36eBJQ6iJxZadoKsJFVZuhx
  secret: ECB-W_VA2T-bIPggTTF4vNv5jF_-OkewE3CHgGnJpqEC9-C20-tw-L0v6paGvz0o__b1BAM9l2CzQmnr